before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfftw3-dev
language: ruby
cache: bundler

os:
  - linux
  - osx

addons:
  apt:
    packages: libfftw3-dev
  homebrew:
    packages: fftw

rvm:
  - "2.2.10"  
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
