language: ruby
cache: bundler

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
    - libfftw3-dev
  homebrew:
    packages:
    - fftw
    update: true

rvm:
  - "2.4.5"
  - "2.5.5"
  - "2.6.3"
  - "2.7.1"

